<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 23 Oct 2017 21:25:33 +0000
 */

$conf['title'] = 'PrePostPrint';
$conf['start'] = 'introduction';
$conf['template'] = 'prepostprint';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['translation']['translations'] = 'en fr';
$conf['plugin']['translation']['display'] = 'langcode';
$conf['plugin']['translation']['translateui'] = 1;
$conf['plugin']['translation']['redirectstart'] = 1;
$conf['plugin']['translation']['localabout'] = 1;
$conf['plugin']['translation']['copytrans'] = 1;

// end auto-generated content
